name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_01
      id: test_01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test_01
        setup-command: javac T01.java
        command: java T01
        input: |-
          978-0201498400
          Data Structures and Algorithm Analysis in C
          Mark Allen Weiss
          1996
          Pearson
          yes
          84.21
          20.12
          0
          4.6
        expected-output: 978-0201498400|Data Structures and Algorithm Analysis in
          C|Mark Allen Weiss|1996|Pearson|yes|84.21|20.12|0|4.6
        comparison-method: exact
        timeout: 10
        max-score: 50
    - name: test_02
      id: test_02
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test_02
        setup-command: javac T01.java
        command: java T01
        input: |-
          978-0130895929
          C: A Reference Manual
          Samuel Harbison, Guy Steele Jr.
          2002
          Pearson
          no
          50.19
          11.05
          21
          4.1
        expected-output: '978-0130895929|C: A Reference Manual|Samuel Harbison, Guy
          Steele Jr.|2002|Pearson|no|50.19|11.05|21|4.1'
        comparison-method: exact
        timeout: 10
        max-score: 50
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_01_RESULTS: "${{steps.test_01.outputs.result}}"
        TEST_02_RESULTS: "${{steps.test_02.outputs.result}}"
      with:
        runners: test_01,test_02
